### ISSUE TITLE
Mise en place de l'installation via ansible

### ISSUE THREAD

**Issue by darkweak** [ZrH-Source/install-vm#2]
Lancer un playbook ansible qui se chargera de se connecter au proxmox puis de lancer une étape afin de provisionner et démarrer une VM via l'attribut `command`
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#examples
La commande à lancer sera 
`qm create  100  --name debian --cdrom local:iso/debian-11.3.0-amd64-netinst.iso --memory 2048 --socket 2`

**Comment by ZrH-Source** [comment]
#!/bin/bash
echo 'Installing ansible.'
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible 

echo 'Running Ansible playbook.'
sudo ansible-playbook -i hosts.ini install-vm.yml
